#!/bin/bash
#### Bash for L2 binning of MODIS OC and SST files for 2016, 2017 and 2018

## Change directory to 2016 OC
cd /media/sf_DISS/barents_data_2016/OC
## Loop through previously created OC .txt files as inputs for L2 bin processor
for i in {2016001..2016366}
do
    l2bin ifile=A${i}.L2_LAC_OC.txt ofile=A${i}.L3b_OC.nc qual_max=3 resolution=4 prodtype=regional
done

## Change directory to 2016 SST
cd /media/sf_DISS/barents_data_2016/SST
## Loop through previously created SST .txt files as inputs for L2 bin processor
for i in {2016001..2016366}
do
    l2bin ifile=A${i}.txt ofile=A${i}.L3b_SST.nc qual_max=3 resolution=4 prodtype=regional
done

#### Repeat for Years 2017 and 2018
## 2017
cd /media/sf_DISS/barents_data_2017/OC
for i in {2017001..2017365}
do
    l2bin ifile=A${i}.L2_LAC_OC.txt ofile=A${i}.L3b_OC.nc qual_max=3 resolution=4 prodtype=regional
done
cd /media/sf_DISS/barents_data_2017/SST
for i in {2017001..2017365}
do
    l2bin ifile=A${i}.txt ofile=A${i}.L3b_SST.nc qual_max=3 resolution=4 prodtype=regional
done

##2018
cd /media/sf_DISS/barents_data_2018/OC
for i in {2018001..2018365}
do
    l2bin ifile=A${i}.L2_LAC_OC.txt ofile=A${i}.L3b_OC.nc qual_max=3 resolution=4 prodtype=regional
done

cd /media/sf_DISS/barents_data_2018/SST
for i in {2018001..2018365}
do
    l2bin ifile=A${i}.txt ofile=A${i}.L3b_SST.nc qual_max=3 resolution=4 prodtype=regional
done
