#!/bin/bash
# Bash Script to create .txt files for OC and SST L2 Files for 2016, 2017
# and 2018 to then be used as inputs for SeaDAS L2bin processor

#### Change directory to 2016 L2 OC Modis files
cd /media/sf_DISS/barents_data_2016/OC

#### Create .txt files with OC file names for each day of the year
for i in {2016001..2016366}
do
  ls A${i}*.L2_LAC_OC.nc > A${i}.L2_LAC_OC.txt
done

#### Change directory to 2016 L2 SST Modis files
cd /media/sf_DISS/barents_data_2016/SST

#### Create .txt files with SST file names for each day of the year
for i in {2016001..2016366}
do
  ls A${i}*.L2_LAC_SST.nc > A${i}.L2_LAC_SST.txt 
done

#### Repeat for years 2017 and 2018
## 2017
cd /media/sf_DISS/barents_data_2017/OC
for i in {2017001..2017365}
do
  ls A${i}*.L2_LAC_OC.nc > A${i}.L2_LAC_OC.txt
done

cd /media/sf_DISS/barents_data_2017/SST
for i in {2017001..2017365}
do
  ls A${i}*.L2_LAC_SST.nc > A${i}.L2_LAC_SST.txt
done

## 2018
cd /media/sf_DISS/barents_data_2018/OC
for i in {2018001..2018365}
do
  ls A${i}*.L2_LAC_OC.nc > A${i}.L2_LAC_OC.txt
done

cd /media/sf_DISS/barents_data_2018/SST
for i in {2018001..2018365}
do
  ls A${i}*.L2_LAC_SST.nc > A${i}.L2_LAC_SST.txt
done