#!/bin/bash
# Bash Script to create mapped 5-day images from previously created L3 binned OC
# and SST files. Once mapped these can be used for NPP model input

#### Change directory to 2016 L3b OC Files
cd/media/sf_DISS/barents_data_2016/OC/L3b
#### Loop through binned files to create mapped OC images with L3 mapgen processor
for i in {2016001..2016366}
do
    l3mapgen ifile=A${i}.5d.L3b_OC.nc ofile=A${i}.5d.L3m_OC.nc resolution=4km north=+89 south=+52 east=+67 west=+10
done

#### Change directory to 2016 L3b SST Files
cd/media/sf_DISS/barents_data_2016/SST/L3b
#### Loop through binned files to create mapped SST images with L3 mapgen processor
for i in {2016001..2016366}
do
    l3mapgen ifile=A${i}.5d.L3b_SST.nc ofile=A${i}.5d.L3m_SST.nc resolution=4km north=+89 south=+52 east=+67 west=+10
done

#### Repeat for 2017 and 2018
## 2017
cd/media/sf_DISS/barents_data_2017/OC/L3b
for i in {2017001..2017365}
do
    l3mapgen ifile=A${i}.5d.L3b_OC.nc ofile=A${i}.5d.L3m_OC.nc resolution=4km north=+89 south=+52 east=+67 west=+10
done

cd/media/sf_DISS/barents_data_2017/SST/L3b
for i in {2017001..2017365}
do
    l3mapgen ifile=A${i}.5d.L3b_SST.nc ofile=A${i}.5d.L3m_SST.nc resolution=4km north=+89 south=+52 east=+67 west=+10
done

## 2018
cd/media/sf_DISS/barents_data_2018/OC/L3b
for i in {2018001..2018365}
do
l3mapgen ifile=A${i}.5d.L3b_OC.nc ofile=A${i}.5d.L3m_OC.nc resolution=4km north=+89 south=+52 east=+67 west=+10
done

cd/media/sf_DISS/barents_data_2018/SST/L3b
for i in {2018001..2018365}
do
l3mapgen ifile=A${i}.5d.L3b_SST.nc ofile=A${i}.5d.L3m_SST.nc resolution=4km north=+89 south=+52 east=+67 west=+10
done
